#============ 数据库配置#======================================
spring:
  datasource:
    url: jdbc:sqlserver://172.17.4.210:1433;DatabaseName=wms
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: wmspj
    password: ENC(czm6/0sHAsvYV/OfkpmsNg==)


  #启动Spring MVC多文件上传
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: D:/LevdeoWms/upload        #指定默认上传的文件夹
      max-file-size: 5MB      #限制单个文件最大大小
      max-request-size: 20MB  #限制所有文件最大大小
      resolve-lazily: false   #是否延迟多部件文件请求的参数和文件的解析

#
mybatis-plus:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#==================== 日志配合·标准  ===========================
logging:
  config: classpath:logback-spring-dev.xml

#自己配置
my:
  #条码路径
  barcodepath: D:/LevdeoWms/barcode/
  #同步 物料主数据、客户主数据 job执行时间每个整点执行一次：秒、分、时、月份中的几号、月份、星期几(周天:1)、年份(1970-2099 可缺省)
  sapSyncWmsScheduleconn: 0 0 0/1 * * ?
